# Generated by Django 3.2.15 on 2024-04-05 17:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_ingredientrecipe_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientrecipe',
            name='amount',
            field=models.PositiveSmallIntegerField(help_text='Укажите количество выбранного ингредиента', validators=[django.core.validators.MinValueValidator(1, 'Количество ингредиента не может быть меньше одного'), django.core.validators.MaxValueValidator(1000, 'Количество ингредиента не может быть больше тысячи')], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(help_text='Введите время приготовления блюда в минутах', validators=[django.core.validators.MinValueValidator(1, 'Время приготовления не может быть меньше минуты')], verbose_name='Время приготовления'),
        ),
    ]
