# Generated by Django 3.2.16 on 2024-04-10 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20240407_2148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ('user',), 'verbose_name': 'Избранный рецепт', 'verbose_name_plural': 'Избранные рецепты'},
        ),
        migrations.AlterModelOptions(
            name='ingredientrecipe',
            options={'ordering': ('ingredient',), 'verbose_name': 'Соответствие рецепта и ингредиента', 'verbose_name_plural': 'Соответствие рецептов и ингредиентов'},
        ),
    ]
